=== donovanhubbard/high-school-code/original-code/assignments/Module 16/units.xsd
<?xml version="1.0" ?>
<!-- XML Schema for units -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
   <xs:element name="units">
      <xs:complexType>
         <xs:sequence>
            <xs:element name="unit" minOccurs="1" maxOccurs="unbounded">
               <xs:complexType>
                  <xs:sequence>
                     <xs:element name="race" type="xs:string" minOccurs="1" maxOccurs="1" />
                     <xs:element name="hp" type="xs:string" minOccurs="1" maxOccurs="1" />
                     <xs:element name="damage" type="xs:string" minOccurs="1" maxOccurs="1" />
                     <xs:element name="image" type="xs:string" minOccurs="1" maxOccurs="1" />
                  </xs:sequence>
                <xs:attribute name="name" type="xs:string" use="required" />
               </xs:complexType>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
</xs:schema>

=== donovanhubbard/high-school-code/original-code/assignments/Module 16/Units.xml
<?xml version="1.0"?>
<!-- Warcraft 3 units -->
<!-- this is the reference to the style sheet -->
<?xml-stylesheet type="text/xsl" href="units.xsl" ?>
<!--this is the reference to the shcema (XSD)-->
<units xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="units.xsd">

	<unit name="Footman">
		<race>Human</race>
		<hp>420</hp>
		<damage>12.5</damage>
		<image>http://www.battle.net/war3/images/human/units/animations/footman.gif</image>
	</unit>
	<unit name="Grunt">
		<race>Orc</race>
		<hp>700</hp>
		<damage>19.5</damage>
		<image>http://www.battle.net/war3/images/orc/units/animations/grunt.gif</image>
	</unit>
	<unit name="Ghoul">
		<race>Undead</race>
		<hp>340</hp>
		<damage>13</damage>
		<image>http://www.battle.net/war3/images/undead/units/animations/ghoul.gif</image>
	</unit>
	<unit name="Archer">
		<race>Night Elf</race>
		<hp>245</hp>
		<damage>17</damage>
		<image>http://www.battle.net/war3/images/nightelf/units/animations/archer.gif</image>
	</unit>

</units>
